### ISSUE TITLE
"script.module.pydes" Abhängigkeits Fehler

### ISSUE THREAD

**Issue by Ron801** [Pati/plugin.video.tvnow.de#3]
Auf einem frischen Kodi18 ist es nicht möglich TVNow aus dem pati Repo zu installieren
Es kommt die Meldung: "script.module.pydes" Abhängihkeit fehlgeschlagen

Nach manueller Installation des scripts läuft auch die Installation von TVNow

**Comment by Pati** [comment]
pydes ist "nur" im Kodinerds repository verfügbar aber nicht offiziellen Kodi repository. Die neuste Version verwendet jetzt cryptodome, also sollte das Problem behoben sein.

**Comment by CodieLAB** [comment]
Woher bekomme ich diese Script.module.pydev? Oberes hat's nicht und Version 3.4.1 will Python v2iwas was ja fals , alt ist
